{% set name = "kedro-neptune" %}
{% set package_name = "kedro_neptune" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: c3ee0db42d8fa9a09c3bfd9d210fc8e623780cb8bcfe12491505dfef4b9ece1b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.6
    - neptune-client >=0.10.9
    - kedro >=0.17.0
    - ruamel.yaml ==0.17.10
    - click >=7.0.0
    - psutil >=5.8.0

test:
  imports:
    - kedro_neptune
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Kedro
  doc_url: https://docs.neptune.ai/integrations-and-supported-tools/
  dev_url: https://github.com/neptune-ai/kedro-neptune

extra:
  recipe-maintainers:
    - HubertJaworski
    - shnela
    - pitercl
    - twolodzko
    - AleksanderWWW
    - PatrykGala
    - Raalsky
